# Generated by Django 2.2.1 on 2019-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='teacher',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_headshot/'),
        ),
    ]
