# Generated by Django 2.2.1 on 2019-06-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20190611_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_picture',
        ),
    ]
