# Generated by Django 2.2.1 on 2019-06-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='student',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='student_headshot/'),
        ),
    ]
